#
# Production server with UWSGI configured to run on port 8080
# and web configured to run directly on port 80
#
# docker-compose build
# docker-compose up -d web
#
# See accompanying Make commands for easy collectstatic etc.

version: '3.7'
volumes:
  geoserver-datadir:
  rabbitmq:
  static-data:
  media-data:
  geocontext-scheduler-data:
x-common-django:
  &default-common-django
  image: bims_uwsgi:latest
  build:
    context: ../
    dockerfile: deployment/docker/Dockerfile
  command: uwsgi --ini /home/web/django_project/uwsgi.ini
  hostname: uwsgi
  working_dir: /home/web/django_project
  environment:
    - ADMIN_EMAILS=${ADMIN_EMAILS:-dimas@kartoza.com}
    - APP_NAME=bims
    - ASYNC_SIGNALS=True
    - BROKER_URL=amqp://rabbitmq:5672
    - C_FORCE_ROOT=1
    - CONTACT_US_EMAIL=${ADMIN_EMAILS:-dimas@kartoza.com}
    - ALLOWED_HOSTS=['django-bims.test']
    - DATABASE_HOST=db
    - DATABASE_NAME=${POSTGRES_DBNAME:-gis}
    - DATABASE_PASSWORD=${POSTGRES_PASS:-docker}
    - DATABASE_URL=postgis://${POSTGRES_USER:-docker}:${POSTGRES_PASS:-docker}@db:5432/${POSTGRES_DBNAME:-gis}
    - DATABASE_USERNAME=${POSTGRES_USER:-docker}
    - DJANGO_SETTINGS_MODULE=core.settings.prod_docker
    - GEOCONTEXT_URL=${GEOCONTEXT_URL:-https://geocontext.kartoza.com}
    - GEOSERVER_LOCATION=http://geoserver/geoserver/
    - GEOSERVER_LOCATION_SITE_LAYER=bims:location_site_view
    - GEOSERVER_PUBLIC_LOCATION=http://django-bims.test/geoserver/
    - GEOSERVER_ADMIN_USER=${GEOSERVER_USERNAME:-admin}
    - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_PASSWORD:-admingeoserver}
    - MEDIA_ROOT=/home/web/media
    - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
    - ROOT_URLCONF=core.urls
    - SITEURL=http://django-bims.test/
    - STATIC_ROOT=/home/web/static/static
    - VIRTUAL_HOST=bims.kartoza.com
    - VIRTUAL_PORT=8080
    - CSRF_TRUSTED_ORIGINS=['django-bims.test']
  volumes:
    - static-data:/home/web/static
    - media-data:/home/web/media
    - ./logs:/var/log/
  links:
    - db:db
    - geoserver:geoserver
    - rabbitmq:rabbitmq
    - cache:cache
    - worker:worker
    - searchworker:searchworker
    - geocontextworker:geocontextworker
  restart: unless-stopped
  user: root

services:

  db:
    container_name: bims_db
    image: kartoza/postgis:16-3.4
    shm_size: 1g
    environment:
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_PASS: ${POSTGRES_PASS:-docker}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME:-gis}
    volumes:
      - ./pg/postgres_data:/var/lib/postgresql
      - ./backups:/backups
      - ./sql:/sql
    ports:
      - "6543:5432"

  geoserver:
    image: kartoza/geoserver:2.24.4
    restart: unless-stopped
    environment:
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
      - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
      - GEOSERVER_CONTEXT_ROOT=${GEOSERVER_CONTEXT_ROOT}
      - ROOT_WEBAPP_REDIRECT=true
      - CONSOLE_HANDLER_LEVEL=${CONSOLE_HANDLER_LEVEL}
    depends_on:
      - db
    volumes:
      - geoserver-datadir:/opt/geoserver/data_dir

  uwsgi:
    <<: *default-common-django

  worker:
    <<: *default-common-django
    entrypoint: [ ]
    hostname: worker
    command: celery --app=bims.celery:app worker -Q update -B -l debug
    links:
      - db:db
      - geoserver:geoserver
      - rabbitmq:rabbitmq
      - cache:cache
    volumes:
      - ../../django-bims:/home/web/django_project
      - ./static:/home/web/static:rw
      - ./media:/home/web/media:rw
      - ./logs:/var/log/

  geocontextworker:
    <<: *default-common-django
    entrypoint: [ ]
    hostname: worker
    command: celery --app=bims.celery:app worker --schedule /home/geocontext-scheduler/celerybeat-schedule -Q geocontext -B -l debug
    links:
      - db:db
      - geoserver:geoserver
      - rabbitmq:rabbitmq
      - cache:cache
    volumes:
      - ../../django-bims:/home/web/django_project
      - ./static:/home/web/static:rw
      - ./media:/home/web/media:rw
      - ./logs:/var/log/
      - geocontext-scheduler-data:/home/geocontext-scheduler

  searchworker:
    <<: *default-common-django
    entrypoint: [ ]
    hostname: worker
    command: celery --app=bims.celery:app worker -Q search -B -l debug
    links:
      - db:db
      - geoserver:geoserver
      - rabbitmq:rabbitmq
      - cache:cache
    volumes:
      - ../../django-bims:/home/web/django_project
      - ./static:/home/web/static:rw
      - ./media:/home/web/media:rw
      - ./logs:/var/log/

  webpack-watcher:
    <<: *default-common-django
    entrypoint: [ ]
    command: bash -c 'cd /home/web/django_project/bims/; webpack --mode development && webpack --watch --progress'
    volumes:
      - ../../django-bims:/home/web/django_project
      - ./static:/home/web/static:rw
      - ./media:/home/web/media:rw
      - ./logs:/var/log/

  dbbackups:
    image: kartoza/pg-backup:16-3.4
    hostname: pg-backups
    links:
      - db:db
    environment:
      # take care to let the project name below match that
      # declared in the top of the makefile
      - DUMPPREFIX=PG_bims
      # These are all defaults anyway, but setting explicitly in
      # case we ever want to ever use different credentials
      - PGUSER=${POSTGRES_USER:-docker}
      - PGPASSWORD=${POSTGRES_PSS:-docker}
      - PGPORT=5432
      - PGHOST=db
      - PGDATABASE=${POSTGRES_DBNAME:-gis}
    restart: unless-stopped

  # This is normally the main entry point for a production server
  web:
    image: nginx
    hostname: nginx
    links:
      - uwsgi:uwsgi"
    restart: unless-stopped
    volumes:
      - static-data:/home/web/static
      - media-data:/home/web/media

  rabbitmq:
    image: rabbitmq:3.7-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: on-failure

  cache:
   image: memcached
   entrypoint:
    - memcached
    - -m 64
